import Card from "../ui/Card";

export default function HotelCard() {
  const hotels = [
    {
      name: "DoubleTree by Hilton Phoenix Midtown",
      location: "Phoenix, AZ",
      phone: "(602) 279-9811",
      rating: "3-Star Hotel",
      rooms: 156,
      image: "/images/Hotels/Hilton.avif",
      link: "https://www.hilton.com/en/hotels/phxardt-doubletree-phoenix-midtown/",
      status: "Current",
    },

    {
      name: "Coronado Inn",
      location: "San Diego, CA",
      phone: "619-435-4121",
      rating: "1-Star Hotel",
      rooms: 31,
      image: "/images/Hotels/CoronadoInn.jpg",
      link: "https://coronadoinn.com/",
      status: "Current",
    },
    {
      name: "Wyndham Garden San Diego SeaWorld",
      location: "San Diego, CA",
      phone: "(619) 881-6100",
      rating: "3-Star Hotel",
      rooms: 316,
      image: "/images/Hotels/Wyndham.avif",
      link: "https://www.wyndhamhotels.com/wyndham-garden/san-diego-california/wyndham-garden-san-diego-near-seaworld/overview",
      status: "Current",
    },
    {
      name: "DoubleTree by Hilton Hotel Newark - Fremont",
      location: "Newark, CA ",
      phone: "(510) 490-8390",
      rating: "3.5-Star Hotel",
      rooms: 315,
      image: "/images/Hotels/DoubleTree.avif",
      link: "https://www.hilton.com/en/hotels/nwkbddt-doubletree-newark-fremont/?SEO_id=GMB-AMER-DT-NWKBDDT&y_source=1_MTYwNzI5Mi03MTUtbG9jYXRpb24ud2Vic2l0ZQ%3D%3D",
      status: "Current",
    },
    {
      name: "Home2 Suites by Hilton San Antonio North Stone Oak",
      location: "San Antonio, TX",
      phone: "(210) 497-4000",
      rating: "3-Star Hotel",
      rooms: 106,
      image: "/images/Hotels/Home2.avif",
      link: "https://www.hilton.com/en/hotels/phxardt-doubletree-phoenix-midtown/",
      status: "Current",
    },
    {
      name: "DoubleTree Pleasanton at the Club",
      location: "Pleasanton, CA",
      phone: "(925) 463-8000",
      rating: "3.5-Star Hotel",
      rooms: 292,
      image: "/images/Hotels/doubletree-pleasanton-hotel.avif",
      link: "https://www.hilton.com/en/hotels/plepcdt-doubletree-pleasanton-at-the-club/",
      status: "Current",
    },
    {
      name: "Hampton by Hilton Phoenix Airport North",
      location: "Phoenix, AZ",
      phone: "(602) 267-0606",
      rating: "3-Star Hotel",
      rooms: 106,
      image: "/images/Hotels/HamptonbyHiltonPhoenixAirportNorth.avif",
      link: "https://www.hilton.com/en/hotels/phxaphx-hampton-phoenix-airport-north/?SEO_id=GMB-AMER-HX-PHXAPHX&y_source=1_MjA4NDY0Ni03MTUtbG9jYXRpb24ud2Vic2l0ZQ%3D%3D",
      status: "Current",
    },
    {
      name: "Buena Park Grand Hotel & Suites",
      location: "Buena Park, CA",
      phone: "(714) 739-5600",
      rating: "1-Star Hotel",
      rooms: 202,
      image: "/images/Hotels/buena-park-grand-hotel-suites-image-2.jpg",
      link: "https://www.buenaparkgrandhotelsuites.com/",
      status: "Current",
    },

    {
      name: "Coronado Island Inn",
      location: "San Diego, CA",
      phone: "619-435-4121",
      rating: "1-Star Hotel",
      rooms: 14,
      image: "/images/Hotels/coronadoislandinn.jpg",
      link: "https://coronadoislandinn.com/",
      status: "Current",
    },
    {
      name: "Home2 Suites by Hilton El Paso Airport",
      location: "El Paso, Texas",
      phone: "(915) 887-0300",
      rating: "3-Star Hotel",
      rooms: 111,
      image:
        "/images/Hotels/elpapht-home2-suites-el-paso-airport-hotel-day.avif",
      link: "https://www.hilton.com/en/hotels/elpapht-home2-suites-el-paso-airport/?SEO_id=GMB-AMER-HT-ELPAPHT&y_source=1_NDQ2NjA2Mi03MTUtbG9jYXRpb24ud2Vic2l0ZQ%3D%3D",
      status: "Current",
    },
    {
      name: "Hampton Inn & Suites Corsicana",
      location: "Corsicana, Texas",
      phone: "(903) 872-2238",
      rating: "3-Star Hotel",
      rooms: 79,
      image: "/images/Hotels/holiday-inn-express-and-suites-corsicana.avif",
      link: "https://www.ihg.com/holidayinnexpress/hotels/us/en/corsicana/crcna/hoteldetail?cm_mmc=GoogleMaps-_-EX-_-US-_-CRCNA",
      status: "Current",
    },
    {
      name: "Holiday Inn Express & Suites Corsicana I-45",
      location: "Corsicana, Texas",
      phone: "(903) 874-7440",
      rating: "3-Star Hotel",
      rooms: 79,
      image: "/images/Hotels/holiday-inn-express-and-suites-corsicana.avif",
      link: "https://www.ihg.com/holidayinnexpress/hotels/us/en/corsicana/crcna/hoteldetail?cm_mmc=GoogleMaps-_-EX-_-US-_-CRCNA",
      status: "Current",
    },

    {
      name: "voco Laguna Hills",
      location: "Laguna, CA",
      phone: "(949) 586-5000",
      rating: "1-Star Hotel",
      rooms: 142,
      image: "/images/Hotels/voco-laguna-hills.jpeg",
      link: "https://www.ihg.com/voco/hotels/us/en/laguna-hills/snalh/hoteldetail?fromRedirect=true&qBrs=6c.hi.ex.sb.ul.ic.cp.cw.in.vn.cv.rs.ki.kd.ma.sp.va.re.vx.nd.sx.we.lx.rn.sn.nu&qSrt=sAV&qDest=laguna%20hills&qErm=false&qRms=1&qAdlt=1&qChld=0&qCiD=28&qCiMy=042025&qCoD=29&qCoMy=042025&qAAR=6CBARC&qRtP=6CBARC&setPMCookies=true&qpMbw=0&qpMn=1&srb_u=1&qRad=30&qRdU=mi",
      status: "Current",
    },

    {
      name: "Drift Thelu Veliga",
      location: "Ari Atoll, Maldives",
      phone: "(949) 586-5000",
      rating: "4.5-Star Hotel",
      rooms: 0,
      image: "/images/Hotels/Drift_013.webp",
      link: "https://www.driftretreat.com/",
      status: "Exited",
    },

    {
      name: "La Quinta Inn & Suites Las Vegas Tropicana",
      location: "Las Vegas, NV",
      phone: "N/A",
      rating: "N/A-Star Hotel",
      rooms: 0,
      image: "/images/Hotels/LaQuintaInn.jpg",
      link: "N/A",
      status: "Exited",
    },

    {
      name: "Crowne Plaza Los Angeles Harbor",
      location: "San Pedro, CA",
      phone: "N/A",
      rating: "3.4-Star Hotel",
      rooms: 244,
      image: "/images/Hotels/crowne-plaza-san-pedro.avif",
      link: "https://www.ihg.com/holidayinnexpress/hotels/us/en/albuquerque/abqww/hoteldetail",
      status: "Exited",
    },
    {
      name: "Americas Best Value Inn",
      location: "Holbrook, AZ",
      phone: "(928) 524-6216",
      rating: "1-Star Hotel",
      rooms: 0,
      image: "/images/Hotels/holiday-inn.avif",
      link: "https://www.radissonhotels.com/en-us/",
      status: "Exited",
    },

    {
      name: "McKinley Grand Hotel",
      location: "Canton, OH",
      phone: "(330) 454-5000",
      rating: "3-Star Hotel",
      rooms: 166,
      image: "/images/Hotels/mckinley-grand-hotel.webp",
      link: "https://www.radissonhotels.com/en-us/",
      status: "Exited",
    },

    {
      name: "Crowne Plaza Tulsa",
      location: "Tulsa, OK",
      phone: "(918) 492-5000",
      rating: "3.5-Star Hotel",
      rooms: 286,
      image: "/images/Hotels/crowneplazatulsa.jpeg",
      link: "https://www.ihg.com/hotels/us/en/reservation?error=sue",
      status: "Exited",
    },

    {
      name: "La Quinta Inn & Suites Canton OH",
      location: "Canton, OH",
      phone: "(330) 492-0151",
      rating: "3-Star Hotel",
      rooms: 98,
      image: "/images/Hotels/la-quinta-inn-suites-canton.webp",
      link: "https://www.ihg.com/hotels/us/en/reservation?error=sue",
      status: "Exited",
    },

    {
      name: "Esplendor Resort at Rio Rico",
      location: "Rio Rico, AZ",
      phone: "+1 520 2811901",
      rating: "3-Star Hotel",
      rooms: 179,
      image: "/images/Hotels/esplendorresort.webp",
      link: "http://www.esplendor-resort.com/",
      status: "Exited",
    },

    {
      name: "Radisson Whittier",
      location: "Whittier, CA",
      phone: "(562) 945-8511",
      rating: "3.5-Star Hotel",
      rooms: 200,
      image: "/images/Hotels/radissonwhittier.webp",
      link: "https://mckinleygrandhotel.com/",
      status: "Exited",
    },
    {
      name: "Fairfield Inn & Suites Yakima",
      location: "Yakima, WA",
      phone: "(509) 452-3100",
      rating: "3-Star Hotel",
      rooms: 81,
      image: "/images/Hotels/FairfieldInn&Suitesyakima.webp",
      link: "https://www.marriott.com/en-us/hotels/ykmfi-fairfield-inn-and-suites-yakima/overview/",
      status: "Exited",
    },

    {
      name: "Folk Inn Ontario Airport",
      location: "Ontario, CA",
      phone: "(909) 937-9700",
      rating: "1-Star Hotel",
      rooms: 0,
      image: "/images/Hotels/FolkInnOntarioAirport.webp",
      link: "https://news.marriott.com/",
      status: "Exited",
    },
    {
      name: "Villaitana Golf & Spa Resort",
      location: "Benidorm, Spain",
      phone: "(509) 452-3100",
      rating: "5-Star Hotel",
      rooms: 238,
      image: "/images/Hotels/mvillaitana-carrusel1.webp",
      link: "https://www.melia.com/es/hoteles/espana/alicante/melia-villaitana/index.html",
      status: "Exited",
    },
    {
      name: "Sheraton Hotel Centro Historico",
      location: "Mexico City, Mexico",
      phone: "N/A",
      rating: "5-Star Hotel",
      rooms: 458,
      image: "/images/Hotels/SheratonHotelCentroHistorico.webp",
      link: "https://www.gracehotels.com/mayflower",
      status: "Exited",
    },

    {
      name: "Mayflower Inn and Spa",
      location: "Washington, CT",
      phone: "(509) 452-3100",
      rating: "5-Star Hotel",
      rooms: 30,
      image: "/images/Hotels/MayflowerInnandSpa.jpeg",
      link: "https://www.extraholidays.com/palm-springs-california/worldmark-palm-springs?lid=gglloc&promoid=google-business-listing",
      status: "Exited",
    },

    {
      name: "The St. Anthony - A Wyndham Historic Hotel",
      location: "Savannah, GA",
      phone: "N/A",
      rating: "4-Star Hotel",
      rooms: 347,
      image: "/images/Hotels/TheStAnthony.webp",
      link: "https://www.thestanthonyhotel.com/lander",
      status: "Exited",
    },

    {
      name: "Hyatt Regency Savannah",
      location: "Washington, CT",
      phone: "N/A",
      rating: "4-Star Hotel",
      rooms: 30,
      image: "/images/Hotels/HyattRegencySavannah.jpeg",
      link: "https://www.hyatt.com/en-US/hotel/georgia/hyatt-regency-savannah/savrs",
      status: "Exited",
    },

    {
      name: "Sheraton Gunter Hotel",
      location: "San Antonio, TX",
      phone: "N/A",
      rating: "4-Star Hotel",
      rooms: 322,
      image: "/images/Hotels/SheratonGunter.webp",
      link: "https://www.marriott.com/en-us/hotels/satgs-sheraton-gunter-hotel-san-antonio/overview/?EM=DNM_SHERATONGUNTER.COM",
      status: "Exited",
    },
    {
      name: "Westward Look Resort",
      location: "Tucson, AZ",
      phone: "N/A",
      rating: "4-Star Hotel",
      rooms: 244,
      image: "/images/Hotels/WestwardLookResort.webp",
      link: "https://www.wyndhamhotels.com/wyndham-grand/tucson-arizona/westward-look-wyndham-grand-resort-and-spa/overview?CID=LC:GR::GGL:RIO:National:46291&iata=00065402",
      status: "Exited",
    },
    {
      name: "Hilton St. Louis Downtown",
      location: "St. Louis, MO",
      phone: "N/A",
      rating: "4-Star Hotel",
      rooms: 195,
      image: "/images/Hotels/hiltonstlouis.webp",
      link: "https://www.starwoodhotels.com/lemeridien/property/rooms/index.html?propertyID=3895&language=en_US",
      status: "Exited",
    },
    {
      name: "The Stoneleigh Hotel & Spa",
      location: "Dallas, TX",
      phone: "N/A",
      rating: "4-Star Hotel",
      rooms: 170,
      image: "/images/Hotels/TheStoneleighHotelSpa.webp",
      link: "https://www.hilton.com/en/hotels/stlddhf-hilton-st-louis-downtown-at-the-arch/",
      status: "Exited",
    },
    {
      name: "Four Points by Sheraton LAX Int'l Airport",
      location: "Los Angeles, CA",
      phone: "N/A",
      rating: "3.5-Star Hotel",
      rooms: 563,
      image: "/images/Hotels/fourpoints-by-sheraton-lax-int.webp",
      link: "https://www.marriott.com/en-us/hotels/laxfp-four-points-los-angeles-international-airport/overview/",
      status: "Exited",
    },
    {
      name: "The Stoneleigh Hotel & Spa",
      location: "Sante Fe, NM",
      phone: "N/A",
      rating: "3-Star Hotel",
      rooms: 128,
      image: "/images/Hotels/TheatSantaFe.webp",
      link: "https://www.choicehotels.com/missouri/branson/hotels?refd=radissonhotelsamericas.com",
      status: "Exited",
    },
    {
      name: "Hotel Plaza Real",
      location: "Sante Fe, NM",
      phone: "N/A",
      rating: "3.5-Star Hotel",
      rooms: 56,
      image: "/images/Hotels/fenewmexicoplazahotel.webp",
      link: "https://www.hotelglorietasantafe.com/lodge-at-santa-fe",
      status: "Exited",
    },

    {
      name: "Radisson Hotel Branson",
      location: "Branson, MO",
      phone: "N/A",
      rating: "3.5-Star Hotel",
      rooms: 472,
      image: "/images/Hotels/RadissonHotelBranson.webp",
      link: "https://www.radissonhotels.com/en-us/hotels/radisson-branson",
      status: "Exited",
    },
    {
      name: "Sheraton Hotel Oklahoma City",
      location: "Oklahoma City, OK",
      phone: "N/A",
      rating: "3.5-Star Hotel",
      rooms: 395,
      image: "/images/Hotels/SheratonHotelCity.webp",
      link: "https://www.marriott.com/en-us/hotels/okcsi-sheraton-oklahoma-city-downtown-hotel/overview/?EM=DNM_SHERATONOKC.COM",
      status: "Exited",
    },
    {
      name: "Nativo Lodge",
      location: "Albuquerque, NM",
      phone: "N/A",
      rating: "3-Star Hotel",
      rooms: 147,
      image: "/images/Hotels/NativoLodge.webp",
      link: "https://www.nativolodge.com/",
      status: "Exited",
    },
    {
      name: "Hilton Melbourne Beach Oceanfront",
      location: "Melbourne, FL",
      phone: "N/A",
      rating: "3.5-Star Hotel",
      rooms: 118,
      image: "/images/Hotels/HiltonMelbourneBeachOceanfront.webp",
      link: "https://www.hilton.com/en/hotels/mlbhihf-hilton-melbourne-beach-oceanfront/",
      status: "Exited",
    },
    {
      name: "Charleston on the Beach Hotel",
      location: "Folly Beach, SC",
      phone: "N/A",
      rating: "3-Star Hotel",
      rooms: 132,
      image: "/images/Hotels/charleston-beach-hotels.webp",
      link: "https://www.charlestoncvb.com/beaches/where-to-stay/charleston-beach-hotels/",
      status: "Exited",
    },
    {
      name: "Sheraton Albuquerque Old Town Hotel",
      location: "Albuquerque, NM",
      phone: "N/A",
      rating: "3.5-Star Hotel",
      rooms: 188,
      image: "/images/Hotels/downtown-albuquerque-hotels.webp",
      link: "https://www.hilton.com/en/hotels/albsmdt-doubletree-albuquerque/",
      status: "Exited",
    },
    {
      name: "DoubleTree Hotel Albuquerque",
      location: "Albuquerque, NM",
      phone: "N/A",
      rating: "3.5-Star Hotel",
      rooms: 295,
      image: "/images/Hotels/dt-hotelexterior11.webp",
      link: "https://www.hilton.com/en/hotels/albsmdt-doubletree-albuquerque/",
      status: "Exited",
    },
    {
      name: "Alexis Park Resort & Spa",
      location: "Las Vegas, NV",
      phone: "N/A",
      rating: "3-Star Hotel",
      rooms: 496,
      image: "/images/Hotels/bfb2f15c57db5d46a591a233eed52ccc.webp",
      link: "https://www.alexispark.com/",
      status: "Exited",
    },
    {
      name: "Hampton Inn & Suites Boerne TX",
      location: "Boerne, TX",
      phone: "N/A",
      rating: "3-Star Hotel",
      rooms: 78,
      image: "/images/Hotels/HamptonInn&BoerneTX.webp",
      link: "hamptoninn3.hilton.com/en/hotels/texas/hampton-inn-and-suites-boerne-SATBOHX/index.html",
      status: "Exited",
    },
    {
      name: "Hilton Toledo",
      location: "Perrysburg, OH",
      phone: "N/A",
      rating: "3-Star Hotel",
      rooms: 184,
      image: "/images/Hotels/gi-2queens-101.webp",
      link: "https://www.hilton.com/en/hotels/tolpbgi-hilton-garden-inn-toledo-perrysburg/",
      status: "Exited",
    },
    {
      name: "Hilton Salt Lake City Airport",
      location: "Salt Lake City, UT",
      phone: "N/A",
      rating: "3-Star Hotel",
      rooms: 278,
      image: "/images/Hotels/dt-lakesideview001.webp",
      link: "https://www.hilton.com/en/hotels/slcapgi-hilton-garden-inn-salt-lake-city-airport/",
      status: "Exited",
    },
    {
      name: "DoubleTree Hotel at Reid Park",
      location: "Tucson, AZ",
      phone: "N/A",
      rating: "3-Star Hotel",
      rooms: 287,
      image: "/images/Hotels/dh-welcome-11.webp",
      link: "https://www.hilton.com/en/hotels/tusbtdt-doubletree-tucson-reid-park/",
      status: "Exited",
    },
    {
      name: "Radisson Hotel Union City",
      location: "Union City, CA",
      phone: "N/A",
      rating: "3-Star Hotel",
      rooms: 265,
      image: "/images/Hotels/RadissonHotelUnionCity.webp",
      link: "https://www.radissonhotels.com/en-us/destination",
      status: "Exited",
    },
    {
      name: "Radisson Hotel O'Hare",
      location: "Chicago, IL",
      phone: "N/A",
      rating: "3-Star Hotel",
      rooms: 246,
      image: "/images/Hotels/ohil-48737959.webp",
      link: "https://www.reservations.com/hotel/radisson-hotel-chicago-ohare?gclid=EAIaIQobChMI2sW17JOV2QIV6LftCh2kAAy1EAAYASAAEgIKqfD_BwE",
      status: "Exited",
    },
    {
      name: "Hilton Las Cruces",
      location: "Las Cruces, NM",
      phone: "N/A",
      rating: "4-Star Hotel",
      rooms: 203,
      image: "/images/Hotels/stay-hgi-lascruces-0111.webp",
      link: "https://www.hilton.com/en/hotels/lrulcgi-hilton-garden-inn-las-cruces/",
      status: "Exited",
    },
    {
      name: "Radisson Hotel Stockton",
      location: "Stockton, CA",
      phone: "N/A",
      rating: "3-Star Hotel",
      rooms: 198,
      image: "/images/Hotels/hiltonstoctonexterior.webp",
      link: "https://www.hilton.com/en/hotels/scksthf-hilton-stockton/",
      status: "Exited",
    },
    {
      name: "Radisson Hotel Stockton",
      location: "Las Cruces, NM",
      phone: "N/A",
      rating: "4-Star Hotel",
      rooms: 203,
      image: "/images/Hotels/stay-hgi-lascruces-0111.webp",
      link: "https://www.hilton.com/en/hotels/lrulcgi-hilton-garden-inn-las-cruces/",
      status: "Exited",
    },
    {
      name: "Hilton Hotel Newark",
      location: "Newark, CA",
      phone: "N/A",
      rating: "3.5-Star Hotel",
      rooms: 312,
      image: "/images/Hotels/newark.webp",
      link: "https://www.hilton.com/en/",
      status: "Exited",
    },
    {
      name: "Hilton Garden Inn Rancho Mirage",
      location: "Rancho Mirage, CA",
      phone: "N/A",
      rating: "3-Star Hotel",
      rooms: 120,
      image: "/images/Hotels/hilton-garden.webp",
      link: "https://www.hilton.com/en/hotels/psprmgi-hilton-garden-inn-palm-springs-rancho-mirage/",
      status: "Exited",
    },
    {
      name: "Howard Johnson LAX Int'l Airport",
      location: "Los Angeles, CA",
      phone: "N/A",
      rating: "3-Star Hotel",
      rooms: 155,
      image: "/images/Hotels/howard-johnson-.webp",
      link: "https://www.wyndhamhotels.com/airports/hotels-near-los-angeles-international-airport-lax",
      status: "Exited",
    },
    {
      name: "Hilton Garden Inn Temple Terrace",
      location: "Tampa, FL",
      phone: "N/A",
      rating: "3-Star Hotel",
      rooms: 148,
      image: "/images/Hotels/hilton-garden-inn.webp",
      link: "https://www.hilton.com/en/hotels/tpanhgi-hilton-garden-inn-tampa-north/",
      status: "Exited",
    },
    {
      name: "Four Points by Sheraton Orlando Studio City",
      location: "Orlando, FL",
      phone: "N/A",
      rating: "3.5-Star Hotel",
      rooms: 302,
      image: "/images/Hotels/fourpoints-by.webp",
      link: "https://www.marriott.com/en-us/hotels/mcofp-four-points-orlando-international-drive/overview/",
      status: "Exited",
    },
    {
      name: "Days Inn Elizabethtown",
      location: "Elizabethtown, KY",
      phone: "N/A",
      rating: "2.5-Star Hotel",
      rooms: 120,
      image: "/images/Hotels/days-inn.webp",
      link: "https://www.wyndhamhotels.com/days-inn/elizabethtown-kentucky/days-inn-elizabethtown/overview?CID=LC:DI::GGL:RIO:National:06068&iata=00065402",
      status: "Exited",
    },
    {
      name: "Days Inn Hotel Circle",
      location: "Albuquerque, NM",
      phone: "N/A",
      rating: "2.5-Star Hotel",
      rooms: 76,
      image: "/images/Hotels/DaysInnHotelCircle.webp",
      link: "https://www.wyndhamhotels.com/days-inn/albuquerque-new-mexico/days-inn-albuquerque-northeast/overview?CID=LC:DI:20160927:RIO:Local:SM-dimotn",
      status: "Exited",
    },
    {
      name: "Days Inn Albuquerque West",
      location: "Albuquerque, NM",
      phone: "N/A",
      rating: "2.5-Star Hotel",
      rooms: 81,
      image: "/images/Hotels/days-inn-west.webp",
      link: "https://www.wyndhamhotels.com/hotels/albuquerque-new-mexico?brand_id=DI",
      status: "Exited",
    },
    {
      name: "Holiday Inn Express Albuquerque",
      location: "Albuquerque, NM",
      phone: "N/A",
      rating: "3-Star Hotel",
      rooms: 104,
      image: "/images/Hotels/holiday-inn-express.webp",
      link: "https://www.ihg.com/holidayinnexpress/hotels/us/en/albuquerque/abqww/hoteldetail",
      status: "Exited",
    },
    {
      name: "Ramada Inn Downtown",
      location: "Albuquerque, NM",
      phone: "N/A",
      rating: "2.5-Star Hotel",
      rooms: 135,
      image: "/images/Hotels/ramada-albuquerque-east.webp",
      link: "https://www.wyndhamhotels.com/ramada/albuquerque-new-mexico/ramada-albuquerque-airport/overview?CID=LC:RA::GGL:RIO:National:47007&iata=00065402",
      status: "Exited",
    },
    {
      name: "Radisson Hotel Cincinnati",
      location: "Cincinnati, OH",
      phone: "N/A",
      rating: "3-Star Hotel",
      rooms: 350,
      image: "/images/Hotels/radisson-hotel-cincinnati.webp",
      link: "https://www.choicehotels.com/kentucky/covington/radisson-hotels/ky029?refd=radissonhotelsamericas.com",
      status: "Exited",
    },
    {
      name: "Hampton Inn Columbia-Northeast",
      location: "Columbia, SC",
      phone: "N/A",
      rating: "3-Star Hotel",
      rooms: 111,
      image: "/images/Hotels/hampton-inn-columbia-northeast.webp",
      link: "https://www.hilton.com/en/hotels/caenehx-hampton-columbia-northeast-fort-jackson-area/",
      status: "Exited",
    },
    {
      name: "Hilton Garden Inn Nashville Airport",
      location: "Nashville, TN",
      phone: "N/A",
      rating: "3-Star Hotel",
      rooms: 110,
      image: "/images/Hotels/hilton-garden-inn-nashville-airport.webp",
      link: "/",
      status: "Exited",
    },
    {
      name: "Radisson Hotel Pittsburgh Green Tree",
      location: "Nashville, TN",
      phone: "N/A",
      rating: "3-Star Hotel",
      rooms: 110,
      image: "/images/Hotels/hilton-garden-inn-nashville-airport.webp",
      link: "/",
      status: "Exited",
    },
    {
      name: "Prava Hotel Downtown",
      location: "San Diego, CA",
      phone: "N/A",
      rating: "4-Star Hotel",
      rooms: 56,
      image: "/images/Hotels/prava-hotel-san-diego.webp",
      link: "/",
      status: "Exited",
    },
    {
      name: "Holiday Inn Select",
      location: "San Diego, CA",
      phone: "N/A",
      rating: "3-Star Hotel",
      rooms: 318,
      image: "/images/Hotels/holiday-inn-select-san-diego.webp",
      link: "/",
      status: "Exited",
    },
    {
      name: "Hotel Zoso Palm Springs",
      location: "Palm Springs, CA",
      phone: "N/A",
      rating: "3.5-Star Hotel",
      rooms: 163,
      image: "/images/Hotels/zosaplamaspring.webp",
      link: "/",
      status: "Exited",
    },
    {
      name: "Park Plaza Garden of the Gods",
      location: "Colorado Springs, CO",
      phone: "N/A",
      rating: "3-Star Hotel",
      rooms: 200,
      image: "/images/Hotels/park-plaza-garden-of-the-gods.webp",
      link: "/",
      status: "Exited",
    },
    {
      name: "Carefree Resort & Conference Center",
      location: "Carefree, AZ",
      phone: "N/A",
      rating: "3-Star Hotel",
      rooms: 234,
      image: "/images/Hotels/Carefree Resort.webp",
      link: "https://www.carefree-resort.com/",
      status: "Exited",
    },
    {
      name: "Radisson Hotel Stapleton",
      location: "Denver, CO",
      phone: "N/A",
      rating: "3-Star Hotel",
      rooms: 300,
      image: "/images/Hotels/radisson-hotel-stapleton.webp",
      link: "https://www.marriott.com/en-us/hotels/densa-renaissance-denver-hotel-and-conference-center/overview/",
      status: "Exited",
    },
    {
      name: "Continental Surf Hotel",
      location: "Honolulu, HI",
      phone: "N/A",
      rating: "2.5-Star Hotel",
      rooms: 143,
      image: "/images/Hotels/continental-surf-hotel.webp",
      link: "/",
      status: "Exited",
    },
    {
      name: "Kuhio Village Resort",
      location: "Honolulu, HI",
      phone: "N/A",
      rating: "3-Star Hotel",
      rooms: 166,
      image: "/images/Hotels/kuhio-village-resort.webp",
      link: "/",
      status: "Exited",
    },
    {
      name: "Radisson Hotel Resort & Waterpark",
      location: "Albuquerque, NM",
      phone: "N/A",
      rating: "3-Star Hotel",
      rooms: 366,
      image: "/images/Hotels/radisson-hotel-resort-waterpark.webp",
      link: "/",
      status: "Exited",
    },
    {
      name: "Amberly Suites Hotel",
      location: "Albuquerque, NM",
      phone: "N/A",
      rating: "2.5-Star Hotel",
      rooms: 168,
      image: "/images/Hotels/ambwrly.webp",
      link: "/",
      status: "Exited",
    },
    {
      name: "AmeriSuites Hotel",
      location: "Albuquerque, NM",
      phone: "N/A",
      rating: "3-Star Hotel",
      rooms: 125,
      image: "/images/Hotels/AmeriSuites.webp",
      link: "https://www.hyatt.com/hyatt-place/en-US/abqzu-hyatt-place-albuquerque-uptown",
      status: "Exited",
    },
    {
      name: "Albuquerque Grand Airport Hotel",
      location: "Albuquerque, NM",
      phone: "N/A",
      rating: "3.5-Star Hotel",
      rooms: 276,
      image: "/images/Hotels/albuquerque-grand-airport-hotel.webp",
      link: "https://www.marriott.com/en-us/hotels/abqah-sheraton-albuquerque-airport-hotel/overview/?EM=DNM_SHERATONALBUQUERQUEAIRPORT.COM",
      status: "Exited",
    },
    {
      name: "Sheraton Hotel North Charleston",
      location: "Charleston, SC",
      phone: "N/A",
      rating: "3.5-Star Hotel",
      rooms: 296,
      image: "/images/Hotels/sheraton-hotel-north-charleston.webp",
      link: "https://www.resortsandlodges.com/lodging/usa/south-carolina/southeast-south-carolina/sheraton-charleston-airport-hotel-171298.html",
      status: "Exited",
    },
    {
      name: "Ramada Plaza Hotel",
      location: "Forth Worth, TX",
      phone: "N/A",
      rating: "3.5-Star Hotel",
      rooms: 430,
      image: "/images/Hotels/ramada-plaza-hotel-fort-worth.webp",
      link: "https://www.marriott.com/en-us/hotels/dfwds-sheraton-fort-worth-downtown-hotel/overview/?EM=DNM_SHERATONFORTWORTH.COM",
      status: "Exited",
    },
    {
      name: "Radisson Park Plaza Austin North",
      location: "Austin, TX",
      phone: "N/A",
      rating: "3-Star Hotel",
      rooms: 189,
      image: "/images/Hotels/radisson-park-plaza-hotel-north.webp",
      link: "https://www.radissonhotels.com/en-us/brand/park-plaza",
      status: "Exited",
    },
    {
      name: "Prava Suites by the Galleria",
      location: "Dallas, TX",
      phone: "N/A",
      rating: "3.5-Star Hotel",
      rooms: 258,
      image: "/images/Hotels/prava-suites-by-the-galleria4.webp",
      link: "/",
      status: "Exited",
    },
    {
      name: "Radisson Hotel Historic Richmond",
      location: "Richmond, VA",
      phone: "N/A",
      rating: "3.5-Star Hotel",
      rooms: 230,
      image: "/images/Hotels/radisson-hotel-historic-richmond2.webp",
      link: "/",
      status: "Exited",
    },
    {
      name: "Clarion Hotel at the Performing Art Center",
      location: "Forth Worth, TX",
      phone: "N/A",
      rating: "3-Star Hotel",
      rooms: 294,
      image: "/images/Hotels/CA0002EXTERIOR.webp",
      link: "https://www.choicehotels.com/california/anaheim/clarion-hotels/ca002?source=gyxt",
      status: "Exited",
    },
    {
      name: "Comfort Inn East",
      location: "Albuquerque, NM",
      phone: "N/A",
      rating: "2.5-Star Hotel",
      rooms: 121,
      image: "/images/Hotels/comfort-inn-east-albuquerque.webp",
      link: "https://www.choicehotels.com/new-mexico/albuquerque/rodeway-inn-hotels/nm406?source=gyxt",
      status: "Exited",
    },
    {
      name: "Historic Plaza Hotel",
      location: "Las Vegas, NM",
      phone: "N/A",
      rating: "3-Star Hotel",
      rooms: 70,
      image: "/images/Hotels/Plaza-Exteriors.jpg",
      link: "https://www.plazahotellvnm.com/",
      status: "Exited",
    },
    {
      name: "Niagara Crossing Hotel and Spa",
      location: "Las Vegas, NM",
      phone: "716-754-9070",
      rating: "3-Star Hotel",
      rooms: 100,
      image: "/images/Hotels/thumb.webp",
      link: "https://www.niagaracrossinghotelandspa.com/",
      status: "Exited",
    },
    {
      name: "Wyndham Palm Springs",
      location: "Palm Springs, CA",
      phone: "N/A",
      rating: "4-Star Hotel",
      rooms: 410,
      image: "/images/Hotels/renpalmspringsexterior.webp",
      link: "https://www.ihg.com/crowneplaza/hotels/us/en/tulsa/tuleu/hoteldetail?cm_mmc=GoogleMaps-_-CP-_-US-_-TULEU",
      status: "Exited",
    },
    {
      name: "DoubleTree Hotel Downtown San Diego",
      location: "San Diego, CA",
      phone: "N/A",
      rating: "3.5-Star Hotel",
      rooms: 333,
      image: "/images/Hotels/Double trre.webp",
      link: "/",
      status: "Exited",
    },
    {
      name: "Le Méridien Dallas by the Galleria",
      location: "Dallas, Texas",
      phone: "N/A",
      rating: "3-Star Hotel",
      rooms: 258,
      image: "/images/Hotels/Le Méridien Dallas by the Galleria.jpg",
      link: "https://www.marriott.com/en-us/hotels/dalmd-le-meridien-dallas-by-the-galleria/overview/",
      status: "Exited",
    },
    {
      name: "Sheraton Dallas Hotel by the Galleria",
      location: "Dallas, Texas",
      phone: "N/A",
      rating: "3-Star Hotel",
      rooms: 279,
      image: "/images/Hotels/SheratonDallasHotelbytheGalleria.webp",
      link: "https://www.marriott.com/en-us/hotels/dalsl-sheraton-dallas-hotel-by-the-galleria/overview/",
      status: "Exited",
    },
  ];

  return (
    <main className="container mx-auto px-4 py-10">
      <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">
        {hotels.map((hotel, i) => (
          <Card key={i} {...hotel} />
        ))}
      </div>
    </main>
  );
}
