import Card from "../ui/Card";

export default function HotelCard() {
  const hotels = [
    {
      name: "Doubletree by Hilton Phoenix Midtown",
      location: "Phoenix, AZ",
      phone: "(602) 279-9811",
      rating: "3-Star Hotel",
      rooms: 156,
      image: "/images/Hotels/Hilton.avif",
      link: "https://www.hilton.com/en/hotels/phxardt-doubletree-phoenix-midtown/",
      status: "Current",
    },

    {
      name: "Coronado Inn",
      location: "San Diego, CA",
      phone: "619-435-4121",
      rating: "1-Star Hotel",
      rooms: 31,
      image: "/images/Hotels/CoronadoInn.jpg",
      link: "https://coronadoinn.com/",
      status: "Current",
    },
    {
      name: "Wyndham Garden San Diego SeaWorld",
      location: "San Diego, CA",
      phone: "(619) 881-6100",
      rating: "3-Star Hotel",
      rooms: 316,
      image: "/images/Hotels/Wyndham.avif",
      link: "https://www.wyndhamhotels.com/wyndham-garden/san-diego-california/wyndham-garden-san-diego-near-seaworld/overview",
      status: "Current",
    },
    {
      name: "DoubleTree by Hilton Hotel Newark - Fremont",
      location: "Newark, CA ",
      phone: "(510) 490-8390",
      rating: "3.5-Star Hotel",
      rooms: 315,
      image: "/images/Hotels/DoubleTree.avif",
      link: "https://www.hilton.com/en/hotels/nwkbddt-doubletree-newark-fremont/?SEO_id=GMB-AMER-DT-NWKBDDT&y_source=1_MTYwNzI5Mi03MTUtbG9jYXRpb24ud2Vic2l0ZQ%3D%3D",
      status: "Current",
    },
    {
      name: "Home2 Suites by Hilton San Antonio North Stone Oak",
      location: "San Antonio, TX",
      phone: "(210) 497-4000",
      rating: "3-Star Hotel",
      rooms: 106,
      image: "/images/Hotels/Home2.avif",
      link: "https://www.hilton.com/en/hotels/phxardt-doubletree-phoenix-midtown/",
      status: "Current",
    },
    {
      name: "Doubletree Pleasanton at the Club",
      location: "Pleasanton, CA",
      phone: "(925) 463-8000",
      rating: "3.5-Star Hotel",
      rooms: 292,
      image: "/images/Hotels/doubletree-pleasanton-hotel.avif",
      link: "https://www.hilton.com/en/hotels/plepcdt-doubletree-pleasanton-at-the-club/",
      status: "Current",
    },
    {
      name: "Hampton by Hilton Phoenix Airport North",
      location: "Phoenix, AZ",
      phone: "(602) 267-0606",
      rating: "3-Star Hotel",
      rooms: 106,
      image: "/images/Hotels/HamptonbyHiltonPhoenixAirportNorth.avif",
      link: "https://www.hilton.com/en/hotels/phxaphx-hampton-phoenix-airport-north/?SEO_id=GMB-AMER-HX-PHXAPHX&y_source=1_MjA4NDY0Ni03MTUtbG9jYXRpb24ud2Vic2l0ZQ%3D%3D",
      status: "Current",
    },
    {
      name: "Buena Park Grand Hotel & Suites",
      location: "Buena Park, CA",
      phone: "(714) 739-5600",
      rating: "1-Star Hotel",
      rooms: 202,
      image: "/images/Hotels/buena-park-grand-hotel-suites-image-2.jpg",
      link: "https://www.buenaparkgrandhotelsuites.com/",
      status: "Current",
    },

    {
      name: "Coronado Island Inn",
      location: "San Diego, CA",
      phone: "619-435-4121",
      rating: "1-Star Hotel",
      rooms: 14,
      image: "/images/Hotels/coronadoislandinn.jpg",
      link: "https://coronadoislandinn.com/",
      status: "Current",
    },
    {
      name: "Home2 Suites by Hilton El Paso Airport",
      location: "El Paso, Texas",
      phone: "(915) 887-0300",
      rating: "3-Star Hotel",
      rooms: 111,
      image:
        "/images/Hotels/elpapht-home2-suites-el-paso-airport-hotel-day.avif",
      link: "https://www.hilton.com/en/hotels/elpapht-home2-suites-el-paso-airport/?SEO_id=GMB-AMER-HT-ELPAPHT&y_source=1_NDQ2NjA2Mi03MTUtbG9jYXRpb24ud2Vic2l0ZQ%3D%3D",
      status: "Current",
    },
    {
      name: "Hampton Inn & Suites Corsicana",
      location: "Corsicana, Texas",
      phone: "(903) 872-2238",
      rating: "3-Star Hotel",
      rooms: 79,
      image: "/images/Hotels/holiday-inn-express-and-suites-corsicana.avif",
      link: "https://www.ihg.com/holidayinnexpress/hotels/us/en/corsicana/crcna/hoteldetail?cm_mmc=GoogleMaps-_-EX-_-US-_-CRCNA",
      status: "Current",
    },
    {
      name: "Holiday Inn Express & Suites Corsicana I-45",
      location: "Corsicana, Texas",
      phone: "(903) 874-7440",
      rating: "3-Star Hotel",
      rooms: 79,
      image: "/images/Hotels/holiday-inn-express-and-suites-corsicana.avif",
      link: "https://www.ihg.com/holidayinnexpress/hotels/us/en/corsicana/crcna/hoteldetail?cm_mmc=GoogleMaps-_-EX-_-US-_-CRCNA",
      status: "Current",
    },

    {
      name: "voco Laguna Hills",
      location: "Laguna, CA",
      phone: "(949) 586-5000",
      rating: "1-Star Hotel",
      rooms: 142,
      image: "/images/Hotels/voco-laguna-hills.jpeg",
      link: "https://www.ihg.com/voco/hotels/us/en/laguna-hills/snalh/hoteldetail?fromRedirect=true&qBrs=6c.hi.ex.sb.ul.ic.cp.cw.in.vn.cv.rs.ki.kd.ma.sp.va.re.vx.nd.sx.we.lx.rn.sn.nu&qSrt=sAV&qDest=laguna%20hills&qErm=false&qRms=1&qAdlt=1&qChld=0&qCiD=28&qCiMy=042025&qCoD=29&qCoMy=042025&qAAR=6CBARC&qRtP=6CBARC&setPMCookies=true&qpMbw=0&qpMn=1&srb_u=1&qRad=30&qRdU=mi",
      status: "Current",
    },

    {
      name: "Drift Thelu Veliga",
      location: "Ari Atoll, Maldives",
      phone: "(949) 586-5000",
      rating: "4.5-Star Hotel",
      rooms: 0,
      image: "/images/Hotels/Drift_013.webp",
      link: "https://www.driftretreat.com/",
      status: "Exited",
    },

    {
      name: "La Quinta Inn & Suites Las Vegas Tropicana",
      location: "Las Vegas, NV",
      phone: "N/A",
      rating: "N/A-Star Hotel",
      rooms: 0,
      image: "/images/Hotels/LaQuintaInn.jpg",
      link: "N/A",
      status: "Exited",
    },

    {
      name: "Crowne Plaza Los Angeles Harbor",
      location: "San Pedro, CA",
      phone: "N/A",
      rating: "3.4-Star Hotel",
      rooms: 244,
      image: "/images/Hotels/crowne-plaza-san-pedro.avif",
      link: "https://www.ihg.com/holidayinnexpress/hotels/us/en/albuquerque/abqww/hoteldetail",
      status: "Exited",
    },
    {
      name: "Americas Best Value Inn",
      location: "Holbrook, AZ",
      phone: "(928) 524-6216",
      rating: "1-Star Hotel",
      rooms: 0,
      image: "/images/Hotels/holiday-inn.avif",
      link: "https://www.radissonhotels.com/en-us/",
      status: "Exited",
    },

    {
      name: "McKinley Grand Hotel",
      location: "Canton, OH",
      phone: "(330) 454-5000",
      rating: "3-Star Hotel",
      rooms: 166,
      image: "/images/Hotels/mckinley-grand-hotel.webp",
      link: "https://www.radissonhotels.com/en-us/",
      status: "Exited",
    },

    {
      name: "Crowne Plaza Tulsa",
      location: "Tulsa, OK",
      phone: "(918) 492-5000",
      rating: "3.5-Star Hotel",
      rooms: 286,
      image: "/images/Hotels/crowneplazatulsa.jpeg",
      link: "https://www.ihg.com/hotels/us/en/reservation?error=sue",
      status: "Exited",
    },

    {
      name: "La Quinta Inn & Suites Canton OH",
      location: "Canton, OH",
      phone: "(330) 492-0151",
      rating: "3-Star Hotel",
      rooms: 98,
      image: "/images/Hotels/la-quinta-inn-suites-canton.webp",
      link: "https://www.ihg.com/hotels/us/en/reservation?error=sue",
      status: "Exited",
    },

    {
      name: "Esplendor Resort at Rio Rico",
      location: "Rio Rico, AZ",
      phone: "+1 520 2811901",
      rating: "3-Star Hotel",
      rooms: 179,
      image: "/images/Hotels/esplendorresort.webp",
      link: "http://www.esplendor-resort.com/",
      status: "Exited",
    },

    {
      name: "Radisson Whittier",
      location: "Whittier, CA",
      phone: "(562) 945-8511",
      rating: "3.5-Star Hotel",
      rooms: 200,
      image: "/images/Hotels/radissonwhittier.webp",
      link: "https://mckinleygrandhotel.com/",
      status: "Exited",
    },
    {
      name: "Fairfield Inn & Suites Yakima",
      location: "Yakima, WA",
      phone: "(509) 452-3100",
      rating: "3-Star Hotel",
      rooms: 81,
      image: "/images/Hotels/FairfieldInn&Suitesyakima.webp",
      link: "https://www.marriott.com/en-us/hotels/ykmfi-fairfield-inn-and-suites-yakima/overview/",
      status: "Exited",
    },

    {
      name: "Folk Inn Ontario Airport",
      location: "Ontario, CA",
      phone: "(909) 937-9700",
      rating: "1-Star Hotel",
      rooms: 0,
      image: "/images/Hotels/FolkInnOntarioAirport.webp",
      link: "https://news.marriott.com/",
      status: "Exited",
    },
    {
      name: "Villaitana Golf & Spa Resort",
      location: "Benidorm, Spain",
      phone: "(509) 452-3100",
      rating: "5-Star Hotel",
      rooms: 238,
      image: "/images/Hotels/mvillaitana-carrusel1.webp",
      link: "https://www.melia.com/es/hoteles/espana/alicante/melia-villaitana/index.html",
      status: "Exited",
    },
    {
      name: "Sheraton Hotel Centro Historico",
      location: "Mexico City, Mexico",
      phone: "N/A",
      rating: "5-Star Hotel",
      rooms: 458,
      image: "/images/Hotels/SheratonHotelCentroHistorico.webp",
      link: "https://www.gracehotels.com/mayflower",
      status: "Exited",
    },

    {
      name: "Mayflower Inn and Spa",
      location: "Washington, CT",
      phone: "(509) 452-3100",
      rating: "5-Star Hotel",
      rooms: 30,
      image: "/images/Hotels/MayflowerInnandSpa.jpeg",
      link: "https://www.extraholidays.com/palm-springs-california/worldmark-palm-springs?lid=gglloc&promoid=google-business-listing",
      status: "Exited",
    },

    {
      name: "The St. Anthony - A Wyndham Historic Hotel",
      location: "Savannah, GA",
      phone: "N/A",
      rating: "4-Star Hotel",
      rooms: 347,
      image: "/images/Hotels/TheStAnthony.webp",
      link: "https://www.thestanthonyhotel.com/lander",
      status: "Exited",
    },

    {
      name: "Hyatt Regency Savannah",
      location: "Washington, CT",
      phone: "N/A",
      rating: "4-Star Hotel",
      rooms: 30,
      image: "/images/Hotels/HyattRegencySavannah.jpeg",
      link: "https://www.hyatt.com/en-US/hotel/georgia/hyatt-regency-savannah/savrs",
      status: "Exited",
    },

    {
      name: "Sheraton Gunter Hotel",
      location: "San Antonio, TX",
      phone: "N/A",
      rating: "4-Star Hotel",
      rooms: 322,
      image: "/images/Hotels/MayflowerInnandSpa.jpeg",
      link: "https://www.marriott.com/en-us/hotels/satgs-sheraton-gunter-hotel-san-antonio/overview/?EM=DNM_SHERATONGUNTER.COM",
      status: "Exited",
    },
    {
      name: "Westward Look Resort",
      location: "Tucson, AZ",
      phone: "N/A",
      rating: "4-Star Hotel",
      rooms: 244,
      image: "/images/Hotels/WestwardLookResort.webp",
      link: "https://www.wyndhamhotels.com/wyndham-grand/tucson-arizona/westward-look-wyndham-grand-resort-and-spa/overview?CID=LC:GR::GGL:RIO:National:46291&iata=00065402",
      status: "Exited",
    },
    {
      name: "Hilton St. Louis Downtown",
      location: "St. Louis, MO",
      phone: "N/A",
      rating: "4-Star Hotel",
      rooms: 195,
      image: "/images/Hotels/hiltonstlouis.webp",
      link: "https://www.starwoodhotels.com/lemeridien/property/rooms/index.html?propertyID=3895&language=en_US",
      status: "Exited",
    },
    {
      name: "The Stoneleigh Hotel & Spa",
      location: "Dallas, TX",
      phone: "N/A",
      rating: "4-Star Hotel",
      rooms: 170,
      image: "/images/Hotels/TheStoneleighHotelSpa.webp",
      link: "https://www.hilton.com/en/hotels/stlddhf-hilton-st-louis-downtown-at-the-arch/",
      status: "Exited",
    },
    {
      name: "Four Points by Sheraton LAX Int'l Airport",
      location: "Los Angeles, CA",
      phone: "N/A",
      rating: "3.5-Star Hotel",
      rooms: 563,
      image: "/images/Hotels/fourpoints-by-sheraton-lax-int.webp",
      link: "https://www.marriott.com/en-us/hotels/laxfp-four-points-los-angeles-international-airport/overview/",
      status: "Exited",
    },
    {
      name: "The Stoneleigh Hotel & Spa",
      location: "Sante Fe, NM",
      phone: "N/A",
      rating: "3-Star Hotel",
      rooms: 128,
      image: "/images/Hotels/TheatSantaFe.webp",
      link: "https://www.choicehotels.com/missouri/branson/hotels?refd=radissonhotelsamericas.com",
      status: "Exited",
    },
    {
      name: "Hotel Plaza Real",
      location: "Sante Fe, NM",
      phone: "N/A",
      rating: "3.5-Star Hotel",
      rooms: 56,
      image: "/images/Hotels/fenewmexicoplazahotel.webp",
      link: "https://www.hotelglorietasantafe.com/lodge-at-santa-fe",
      status: "Exited",
    },
  ];

  return (
    <main className="container mx-auto px-4 py-10">
      <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">
        {hotels.map((hotel, i) => (
          <Card key={i} {...hotel} />
        ))}
      </div>
    </main>
  );
}
